### ISSUE TITLE
Alternatives to Trading View

### ISSUE THREAD

**Issue by E3V3A** [balupton/automated-trading#2]
Great reading your website & story! 
Accidentally crossed your repo looking for something useful for TradingView, that I've been torturing myself with by trying to do the simplest things in Pine-script with very poor results. I'm interested in the automatic trading stuff, so, what kind of alternatives would you consider looking at?

**Comment by balupton** [comment]
Take a look at the options in the Automated Trading section at https://notes.balupton.com/crypto/ there a bunch now. You should be able to find something that works. The python libraries are very advanced. The Julia languages would be superior, but they are currently under construction.
