### ISSUE TITLE
Use this for scraping data from trading view?

### ISSUE THREAD

**Issue by koren88i** [balupton/automated-trading#3]
first of all - very near and comprehensive explanation of project.

is it possible to use this in order to get monthly adjusted data from trading view by symbol???

**Comment by balupton** [comment]
thanks

unfortunately trading view doesn't offer any export options - however I have another project, currently private, which is scraping various sources and dumping their data into json files in a git repo (currently private)

I'd love to open up the scraper and data dumps, however I am unsure if they violate terms of service or not
